# Generated by Django 5.2.7 on 2026-01-06 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_description_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
